added hass labels for image

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -18,7 +18,7 @@ env:
     
 jobs:
   build:
-    
+    name: Build ${{ matrix.arch }} ${{ github.ref.tags[0] }}
     runs-on: ubuntu-latest
     permissions:
       contents: read
@@ -26,9 +26,12 @@ jobs:
       # This is used to complete the identity challenge
       # with sigstore/fulcio when running outside of PRs.
       id-token: write
-
+    strategy:
+      matrix:
+        # Build for amd64 and arm64 architectures
+        arch: [ 'amd64', 'arm64' ]
     steps:
-      - name: Checkout repository
+      - name: ⤵️ Check out code from GitHub
         uses: actions/checkout@v4
 
       # Install the cosign tool except on PR
@@ -39,13 +42,13 @@ jobs:
         with:
           cosign-release: 'v2.2.4'
 
-      - name: Set up QEMU
+      - name: 🏗 Set up QEMU
         uses: docker/setup-qemu-action@v3
   
       # Set up BuildKit Docker container builder to be able to build
       # multi-platform images and export cache
       # https://github.com/docker/setup-buildx-action
-      - name: Set up Docker Buildx
+      - name: 🏗 Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
       # Login against a Docker registry except on PR
@@ -66,9 +69,21 @@ jobs:
         with:
           images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
 
+      - name: ℹ️ Compose build flags
+        id: flags
+        run: |
+          if [[ "${{ matrix.arch }}" = "amd64" ]]; then
+            echo "platform=linux/amd64" >> $GITHUB_OUTPUT
+          elif [[ "${{ matrix.arch }}" = "aarch64" ]]; then
+            echo "platform=linux/arm64/v8" >> $GITHUB_OUTPUT
+          else
+            echo "::error ::Could not determine platform for architecture ${{ matrix.arch }}"
+            exit 1
+          fi
+
       # Build and push Docker image with Buildx (don't push on PR)
       # https://github.com/docker/build-push-action
-      - name: Build and push Docker image
+      - name: 🚀 Build and push Docker image
         id: build-and-push
         uses: docker/build-push-action@v5
         with:
@@ -76,7 +91,10 @@ jobs:
           push: true
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
-          platforms: linux/amd64,linux/arm64
+          platforms: ${{ steps.flags.outputs.platform }}
+          build-args: |
+            BUILD_ARCH=${{ matrix.arch }}
+            BUILD_VERSION=${{ github.ref.tags[0] }}
 
       # Sign the resulting Docker image digest except on PRs.
       # This will only write to the public Rekor transparency log when the Docker
